name: ai_clone_app
description: "Your Flutter AI Clone Assistant"
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
    sdk: '^3.7.0'
dependencies:
  flutter:
    sdk: flutter

  # Flutter Core Dependencies
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1

  # Firebase Dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: 5.6.5
  google_sign_in: ^6.3.0

  # AI & Voice Dependencies
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  audioplayers: ^6.4.0

  # API Communication
  dio: ^5.8.0+1
  http: ^1.3.0
  googleapis: ^14.0.0
  googleapis_auth: ^1.6.0

  # Android Features
  android_intent_plus: ^5.3.0
  permission_handler: ^11.4.0
  url_launcher: ^6.3.1

  # Chat UI
  flutter_chat_bubble: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
